language: php

php:
  - 5.3
  - 5.4
  - 5.5

notifications:
  email:
    recipients:
      - jeroendedauw@gmail.com
    on_success: change
    on_failure: always
  irc:
    channels:
      - "chat.freenode.net#wikimedia-wikidata"
      - "chat.freenode.net#semantic-mediawiki"
    on_success: change
    on_failure: always